### ISSUE TITLE
Error - The assigned roles field is required.

### ISSUE THREAD

**Issue by abhitheawesomecoder** [savannabits/jig#3]
When I create a user it throws this error

**Comment by abhitheawesomecoder** [comment]
when user create form is rendered this role is there
{
  "id": 1,
  "name": "administrator",
  "title": null,
  "checked": false
}

**Comment by abhitheawesomecoder** [comment]
$roles = Role::all()->map(function ($role) {
            $role->checked = false;
            return $role->only(['id', 'name', 'title', 'checked']);
        })->keyBy('name');

$role->checked is false but why?

**Comment by coolsam726** [comment]
This is an oversight. Basically when creating a user, we are not supposed to assign the user any role. Roles are assigned when editing the user. Let me do a pull request to fix the discrepancies.
